Note to self
[157/248] Building CXX object kadas/app/CMakeFiles/kadas.dir/3d/kadas3dintegration.cpp.o
FAILED: [code=1] kadas/app/CMakeFiles/kadas.dir/3d/kadas3dintegration.cpp.o
/usr/bin/c++ -DMILX_LICENSE_KEY=\"\" -DQT_3DCORE_LIB -DQT_3DEXTRAS_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DRENDER_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -I/run/build/kadas-albireo2 -I/run/build/kadas-albireo2/_flatpak_build -I/run/build/kadas-albireo2/kadas/app -I/run/build/kadas-albireo2/kadas/app/3d -I/run/build/kadas-albireo2/kadas/app/bullseye -I/run/build/kadas-albireo2/kadas/app/external/qgis -I/run/build/kadas-albireo2/kadas/app/guidegrid -I/run/build/kadas-albireo2/kadas/app/iamauth -I/run/build/kadas-albireo2/kadas/app/kml -I/run/build/kadas-albireo2/kadas/app/layertree -I/run/build/kadas-albireo2/kadas/app/mapgrid -I/run/build/kadas-albireo2/kadas/app/mapswipe -I/run/build/kadas-albireo2/kadas/app/milx -I/run/build/kadas-albireo2/_flatpak_build/kadas/app -isystem /run/build/kadas-albireo2/_flatpak_build/kadas/app/kadas_autogen/include -isystem /usr/include/QtWidgets -isystem /usr/include/QtGui -isystem /usr/include/QtCore -isystem /usr/lib/mkspecs/linux-g++ -isystem /usr/include/QtNetwork -isystem /usr/include/QtXml -isystem /usr/include/QtSql -isystem /usr/include/QtOpenGL -isystem /usr/include/QtPrintSupport -isystem /app/include/QuaZip-Qt5-1.5 -isystem /app/include/QuaZip-Qt5-1.5/quazip -isystem /app/include/qgis -isystem /app/include/Qca-qt5/QtCrypto -isystem /usr/include/QtSerialPort -isystem /usr/include/Qt3DCore -isystem /usr/include/Qt3DRender -isystem /usr/include/Qt3DInput -isystem /usr/include/Qt3DLogic -isystem /usr/include/Qt3DExtras -isystem /usr/include/python3.12 -isystem /usr/include/QtSvg -isystem /usr/include/QtConcurrent -isystem /usr/include/librsvg-2.0 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/webp -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/cairo -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O3 -DNDEBUG -fPIC -pthread -DQT_CONCURRENT_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -MD -MT kadas/app/CMakeFiles/kadas.dir/3d/kadas3dintegration.cpp.o -MF kadas/app/CMakeFiles/kadas.dir/3d/kadas3dintegration.cpp.o.d -o kadas/app/CMakeFiles/kadas.dir/3d/kadas3dintegration.cpp.o -c /run/build/kadas-albireo2/kadas/app/3d/kadas3dintegration.cpp
/run/build/kadas-albireo2/kadas/app/3d/kadas3dintegration.cpp: In function ‘void read3DMapViewSettings(Kadas3DMapCanvasWidget*, QDomElement&)’:
/run/build/kadas-albireo2/kadas/app/3d/kadas3dintegration.cpp:89:55: error: no matching function for call to ‘QgsCameraController::readXml(QDomElement&, QgsVector3D&)’
   89 |     widget->mapCanvas3D()->cameraController()->readXml( elemCamera, savedOrigin );
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /run/build/kadas-albireo2/kadas/app/3d/kadas3dintegration.cpp:24:
/app/include/qgis/qgscameracontroller.h:177:10: note: candidate: ‘void QgsCameraController::readXml(const QDomElement&)’
  177 |     void readXml( const QDomElement &elem );
      |          ^~~~~~~
/app/include/qgis/qgscameracontroller.h:177:10: note:   candidate expects 1 argument, 2 provided
/run/build/kadas-albireo2/kadas/app/3d/kadas3dintegration.cpp: In member function ‘Kadas3DMapCanvasWidget* Kadas3DIntegration::createNewMapCanvas3D(const QString&)’:
/run/build/kadas-albireo2/kadas/app/3d/kadas3dintegration.cpp:215:32: warning: ‘void Qgs3DMapSettings::setMaxTerrainScreenError(double)’ is deprecated [-Wdeprecated-declarations]
  215 |   map->setMaxTerrainScreenError( 2.0 );
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
In file included from /run/build/kadas-albireo2/kadas/app/3d/kadas3dintegration.cpp:27:
/app/include/qgis/qgs3dmapsettings.h:293:28: note: declared here
  293 |     Q_DECL_DEPRECATED void setMaxTerrainScreenError( double error ) SIP_DEPRECATED;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~