Added test headers
FAILED: [code=1] tests/src/gui/search/CMakeFiles/test_gui_kadasalternategotolocatorfilter.dir/testkadasalternategotolocatorfilter.cpp.o
/usr/bin/c++ -DCMAKE_SOURCE_DIR=\"/run/build/kadas-albireo2\" -DMILX_LICENSE_KEY=\"\" -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SERIALPORT_LIB -DQT_SVG_LIB -DQT_TESTCASE_BUILDDIR=\"/run/build/kadas-albireo2/_flatpak_build\" -DQT_TESTLIB_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DTEST_DATA_DIR=\"/run/build/kadas-albireo2/tests/tests/testdata\" -I/run/build/kadas-albireo2 -I/run/build/kadas-albireo2/_flatpak_build -isystem /run/build/kadas-albireo2/_flatpak_build/tests/src/gui/search/test_gui_kadasalternategotolocatorfilter_autogen/include -isystem /usr/include/QtWidgets -isystem /usr/include/QtGui -isystem /usr/include/QtCore -isystem /usr/lib/mkspecs/linux-g++ -isystem /usr/include/QtNetwork -isystem /usr/include/QtSvg -isystem /usr/include/QtXml -isystem /usr/include/QtConcurrent -isystem /app/include/QuaZip-Qt5-1.5 -isystem /app/include/QuaZip-Qt5-1.5/quazip -isystem /app/include/qgis -isystem /app/include/Qca-qt5/QtCrypto -isystem /usr/include/QtSerialPort -isystem /usr/include/librsvg-2.0 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/webp -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/cairo -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/QtPrintSupport -isystem /usr/include/QtOpenGL -isystem /usr/include/QtTest -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O3 -DNDEBUG -fPIC -pthread -DQT_CONCURRENT_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -MD -MT tests/src/gui/search/CMakeFiles/test_gui_kadasalternategotolocatorfilter.dir/testkadasalternategotolocatorfilter.cpp.o -MF tests/src/gui/search/CMakeFiles/test_gui_kadasalternategotolocatorfilter.dir/testkadasalternategotolocatorfilter.cpp.o.d -o tests/src/gui/search/CMakeFiles/test_gui_kadasalternategotolocatorfilter.dir/testkadasalternategotolocatorfilter.cpp.o -c /run/build/kadas-albireo2/tests/src/gui/search/testkadasalternategotolocatorfilter.cpp
/run/build/kadas-albireo2/tests/src/gui/search/testkadasalternategotolocatorfilter.cpp:7:10: fatal error: qgstest.h: No such file or directory
    7 | #include <qgstest.h>
      |          ^~~~~~~~~~~
compilation terminated.